# Generated by Django 2.2.5 on 2019-10-01 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('contact', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=100)),
                ('location', models.IntegerField(choices=[(1, 'Copenhagen'), (2, 'Frederiksberg'), (3, 'Albertslund'), (4, 'Ballerup'), (5, 'Brøndby'), (6, 'Furesø'), (7, 'Gentofte'), (8, 'Gladsaxe'), (9, 'Glostrup'), (10, 'Greve Strand'), (11, 'Herlev'), (12, 'Hvidovre'), (13, 'Ishøj'), (14, 'Lyngby-Taarbæk'), (15, 'Rødovre'), (16, 'Rudersdal'), (17, 'Tårnby'), (18, 'Vallensbæk'), (19, 'Skåne'), (20, 'Outside Greater Copenhagen')], default=1)),
                ('postcode', models.CharField(blank=True, max_length=4)),
                ('job_type', models.IntegerField(choices=[(1, 'Not specified'), (2, 'Full-time'), (3, 'Part-time'), (4, 'Student job'), (5, 'Internship')], default=1)),
                ('seniority_level', models.IntegerField(choices=[(1, 'Not specified'), (2, 'Senior'), (3, 'Mid level'), (4, 'Junior'), (5, 'Entry level')], default=1)),
                ('last_application_date', models.DateField()),
                ('apply_link', models.URLField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_job', models.BooleanField(default=False)),
            ],
        ),
    ]
